### ISSUE TITLE
deploy.sh執行問題

### ISSUE THREAD

**Issue by Roach0857** [taipower-dreams-tester/dreams-cloud-joint-tester#63]
以下是執行完deploy.sh後container的Logs
**dreamscloudjointtester_master_1**
```
> loopback-getting-started@1.0.0 start-nossl /rest-api-dreams
> cross-env NODE_ENV=production node .

Plants settings.validateUpsert was overriden to false
Unhandled error for request GET /api/Plants?access_token=top_secret&filter={"fields":["id","plantNo","plantName","gatewayId","dnp3Address"],"include":{"relation":"gateway","scope":{"fields":["ipAddress","port","dnp3Port","powerMeterCTRatio","powerMeterPTRatio"]}}}: Error: Authorization Required
    at /rest-api-dreams/node_modules/loopback/lib/application.js:431:21
    at /rest-api-dreams/node_modules/loopback/lib/model.js:359:7
    at /rest-api-dreams/node_modules/loopback/common/models/acl.js:529:16
    at /rest-api-dreams/node_modules/async/dist/async.js:3888:9
    at /rest-api-dreams/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/rest-api-dreams/node_modules/async/dist/async.js:1064:13)
    at /rest-api-dreams/node_modules/async/dist/async.js:969:16
    at /rest-api-dreams/node_modules/async/dist/async.js:3885:13
    at /rest-api-dreams/node_modules/loopback/common/models/acl.js:511:17
    at /rest-api-dreams/common/models/role.js:327:21
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
**dreamscloudjointtester_mq-dreams_1**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiormq/connection.py", line 231, in connect
    self.url.host, self.url.port, ssl=ssl_context
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 81, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('172.20.0.3', 5672)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dreams-master/mq-dreams/consumer-dreams.py", line 211, in <module>
    loop.run_until_complete(main(loop))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/dreams-master/mq-dreams/consumer-dreams.py", line 163, in main
    amqp_url, loop=loop
  File "/usr/local/lib/python3.6/site-packages/aio_pika/robust_connection.py", line 259, in connect_robust
    client_properties=client_properties, **kwargs
  File "/usr/local/lib/python3.6/site-packages/aio_pika/connection.py", line 324, in connect
    timeout=timeout, client_properties=client_properties, loop=loop
  File "/usr/local/lib/python3.6/site-packages/aio_pika/robust_connection.py", line 123, in connect
    **self.connect_kwargs
  File "/usr/local/lib/python3.6/site-packages/aio_pika/connection.py", line 125, in connect
    timeout=timeout
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/site-packages/aio_pika/connection.py", line 108, in _make_connection
    connection = await aiormq.connect(self.url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/aiormq/connection.py", line 530, in connect
    await connection.connect(client_properties or {})
  File "/usr/local/lib/python3.6/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
  File "/usr/local/lib/python3.6/site-packages/aiormq/connection.py", line 234, in connect
    raise ConnectionError(*e.args) from e
ConnectionError: [Errno 111] Connect call failed ('172.20.0.3', 5672)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiormq/connection.py", line 231, in connect
    self.url.host, self.url.port, ssl=ssl_context
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 81, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('172.20.0.3', 5672)
```
且查看mysql資料庫dreams_business內的**AccessToken**和**Gateway**資料表接為空的
再麻煩除錯，謝謝!

**Comment by Roach0857** [comment]
清空資料表**User**和**Role**後並重新執行deploy.sh運作正常
